/* filename.c(.cpp)/.h(.hpp)
** 文件功能简述
**
** 错误反馈：andy2003du1984@163.com
**
** 作者：
**	杜鹏(Andrew)	07/06/2013
**	商业软件，保留一切权利
** 修改：
**
** http://www.andrew-sh.com
*/

#ifndef IOREMAP_H_
#define IOREMAP_H_
 

/*
 *	< BOOL REMAP SECTION >				
 */
#define 	PL_DATABASE_BOOL_START			DATABASE_BOOL_000
#define 	PL_GETMAINCARD_FLAG     			DATABASE_BOOL_000
#define 	PL_CHRGUNLINKERR_FLAG     			DATABASE_BOOL_001
#define 	PL_NETWORKLINKSTATE_FLAG     		DATABASE_BOOL_002
#define 	PL_NEEDNETWORK_FLAG     			DATABASE_BOOL_003
//#define 	PL_CHRPASSWRDERR_FLAG     			DATABASE_BOOL_004
//#define 	PL_SETPASSWRDERR_FLAG     			DATABASE_BOOL_005

//#define 	PL_DATABASE_BOOL_STOP			DATABASE_BOOL_003
#define   PL_CHRGUNLINK_FLAG					DATABASE_BOOL_004
#define 	PL_APPOINT_FLAG                      DATABASE_BOOL_005
#define 	PL_BACK_FLAG                      DATABASE_BOOL_006
#define   PL_CONNECT_ERR_FLAG           DATABASE_BOOL_007
#define   PL_MONEY_LEFT_FLAG           DATABASE_BOOL_008

#define 	PL_DATABASE_BOOL_STOP			DATABASE_BOOL_008

/*
 *	< UINT8 REMAP SECTION >
 */
#define 	PL_DATABASE_UINT8_START			DATABASE_UINT8_000
#define PL_HMI_PAGE_INDEX					DATABASE_UINT8_000
#define PL_HMI_BUTTON_DOWN				DATABASE_UINT8_001
#define  PL_HMI_CHARG_BY_TIME_TYPE		DATABASE_UINT8_002
#define  PL_HMI_CHARG_BY_ENERGY_TYPE		DATABASE_UINT8_003
#define PL_HMI_PAGE_INDEX_CUR				DATABASE_UINT8_004
#define PL_CHRERROR_STATE					DATABASE_UINT8_005
#define 	PL_CHRPASSWRDERR_FLAG     			DATABASE_UINT8_006
#define 	PL_SETPASSWRDERR_FLAG     			DATABASE_UINT8_007
#define 	PL_CELLTYPE_FLAG     				DATABASE_UINT8_008
#define 	PL_CHRPROCESSCHECK_FLAG     		DATABASE_UINT8_009
#define 	PL_LITTLEWINDOWFUC_FLAG     		DATABASE_UINT8_010
#define 	PL_CARDPROMPT_FLAG     			DATABASE_UINT8_011
#define 	PL_CHRGUNLINKSTATE_FLAG     		DATABASE_UINT8_012
#define 	PL_HMI_CHARG_BY_MONEY_TYPE     	DATABASE_UINT8_013
#define 	PL_HISTORY_CHECK    				DATABASE_UINT8_014
#define 	PL_GETNEEDCHARGUN     				DATABASE_UINT8_015

#define 	PL_STUBISCHARGING_1     					DATABASE_UINT8_016
#define 	PL_STUBISCHARGING_2     					DATABASE_UINT8_017
#define 	PL_STUBISCHARGING_3     					DATABASE_UINT8_018
#define 	PL_STUBISCHARGING_4     					DATABASE_UINT8_019

#define 	PL_GETSTARTSOC_FLAG_1     			    	DATABASE_UINT8_020
#define 	PL_GETSTARTSOC_FLAG_2     					DATABASE_UINT8_021
#define 	PL_GETSTARTSOC_FLAG_3     			    	DATABASE_UINT8_022
#define 	PL_GETSTARTSOC_FLAG_4     					DATABASE_UINT8_023

#define 	PL_STARTSOC_1     									DATABASE_UINT8_024
#define 	PL_STARTSOC_2     									DATABASE_UINT8_025
#define 	PL_STARTSOC_3     									DATABASE_UINT8_026
#define 	PL_STARTSOC_4     									DATABASE_UINT8_027

#define 	PL_TOTALSOC_1     									DATABASE_UINT8_028
#define 	PL_TOTALSOC_2     									DATABASE_UINT8_029
#define 	PL_TOTALSOC_3     									DATABASE_UINT8_030
#define 	PL_TOTALSOC_4     									DATABASE_UINT8_031

#define 	PL_GETSTOPSOC_FLAG_1   					DATABASE_UINT8_032
#define 	PL_GETSTOPSOC_FLAG_2   					DATABASE_UINT8_033
#define 	PL_GETSTOPSOC_FLAG_3   					DATABASE_UINT8_034
#define 	PL_GETSTOPSOC_FLAG_4   					DATABASE_UINT8_035

#define 	PL_STOPSOC_1     										DATABASE_UINT8_036
#define 	PL_STOPSOC_2     										DATABASE_UINT8_037
#define 	PL_STOPSOC_3     										DATABASE_UINT8_038
#define 	PL_STOPSOC_4     										DATABASE_UINT8_039

#define 	PL_CELLTYPE_1     										DATABASE_UINT8_040
#define 	PL_CELLTYPE_2     										DATABASE_UINT8_041
#define 	PL_CELLTYPE_3     										DATABASE_UINT8_042
#define 	PL_CELLTYPE_4     										DATABASE_UINT8_043

#define 	PL_HAVESTARTKWH_FLAG_1     			DATABASE_UINT8_044
#define 	PL_HAVESTARTKWH_FLAG_2     			DATABASE_UINT8_045
#define 	PL_HAVESTARTKWH_FLAG_3     			DATABASE_UINT8_046
#define 	PL_HAVESTARTKWH_FLAG_4     			DATABASE_UINT8_047

#define 	PL_USERCHARGESUCESS_FLAG_1     	DATABASE_UINT8_048
#define 	PL_USERCHARGESUCESS_FLAG_2     	DATABASE_UINT8_049
#define 	PL_USERCHARGESUCESS_FLAG_3     	DATABASE_UINT8_050
#define 	PL_USERCHARGESUCESS_FLAG_4     	DATABASE_UINT8_051

#define 	PL_OLDSTUBISCHARGING_1     			DATABASE_UINT8_052
#define 	PL_OLDSTUBISCHARGING_2     			DATABASE_UINT8_053
#define 	PL_OLDSTUBISCHARGING_3     			DATABASE_UINT8_054
#define 	PL_OLDSTUBISCHARGING_4     			DATABASE_UINT8_055

#define 	PL_HAVESTARTCHARTM_FLAG_1     		DATABASE_UINT8_056
#define 	PL_HAVESTARTCHARTM_FLAG_2     		DATABASE_UINT8_057
#define 	PL_HAVESTARTCHARTM_FLAG_3     		DATABASE_UINT8_058
#define 	PL_HAVESTARTCHARTM_FLAG_4     		DATABASE_UINT8_059

#define 	PL_HAVESTOPCHARTM_FLAG_1  			DATABASE_UINT8_060
#define 	PL_HAVESTOPCHARTM_FLAG_2  			DATABASE_UINT8_061
#define 	PL_HAVESTOPCHARTM_FLAG_3  			DATABASE_UINT8_062
#define 	PL_HAVESTOPCHARTM_FLAG_4  			DATABASE_UINT8_063

#define 	PL_CHARGEGUNLINKSTATE_1     			DATABASE_UINT8_064
#define 	PL_CHARGEGUNLINKSTATE_2     			DATABASE_UINT8_065
#define 	PL_CHARGEGUNLINKSTATE_3     			DATABASE_UINT8_066
#define 	PL_CHARGEGUNLINKSTATE_4     			DATABASE_UINT8_067

#define 	PL_SHOWCHARGEGUN_INDEX     			DATABASE_UINT8_087
#define 	PL_DATABASE_UINT8_STOP				DATABASE_UINT8_087

/*                                              	                      
 *	< UINT16 REMAP SECTION >                    	                      
 */
#define 	PL_DATABASE_UINT16_START		 DATABASE_UINT16_000
#define 	PL_CHRTOTALUSE_TIME				 DATABASE_UINT16_000
#define 	PL_CHR_STATE						 DATABASE_UINT16_001
#define 	PL_CHR_STATRTSOC					 DATABASE_UINT16_002
#define 	PL_CHR_CURRENTSOC					 DATABASE_UINT16_003
#define 	PL_CHR_STOPSOC					 DATABASE_UINT16_004
#define 	PL_CHR_LFTTIME						 DATABASE_UINT16_005

#define 	PL_MOUDLE_WARNING_BYTE_1     	DATABASE_UINT16_006
#define 	PL_MOUDLE_WARNING_BYTE_2     	DATABASE_UINT16_007
#define 	PL_MOUDLE_WARNING_BYTE_3     	DATABASE_UINT16_008
#define 	PL_MOUDLE_WARNING_BYTE_4     	DATABASE_UINT16_009
#define 	PL_MOUDLE_WARNING_BYTE_5     	DATABASE_UINT16_010
#define 	PL_MOUDLE_WARNING_BYTE_6     	DATABASE_UINT16_011
#define 	PL_MOUDLE_WARNING_BYTE_7     	DATABASE_UINT16_012
#define 	PL_MOUDLE_WARNING_BYTE_8      DATABASE_UINT16_013
#define 	PL_MOUDLE_WARNING_BYTE_9      DATABASE_UINT16_014
#define 	PL_MOUDLE_WARNING_BYTE_10    DATABASE_UINT16_015
#define 	PL_MOUDLE_WARNING_BYTE_11   	DATABASE_UINT16_016
#define 	PL_MOUDLE_WARNING_BYTE_12   DATABASE_UINT16_017
#define 	PL_MOUDLE_WARNING_BYTE_13   DATABASE_UINT16_018
#define 	PL_MOUDLE_WARNING_BYTE_14   DATABASE_UINT16_019
#define 	PL_MOUDLE_WARNING_BYTE_15   DATABASE_UINT16_020
#define 	PL_MOUDLE_WARNING_BYTE_16   DATABASE_UINT16_021

#define 	PL_CHRLEFTTM_1   								 DATABASE_UINT16_022
#define 	PL_CHRLEFTTM_2   								 DATABASE_UINT16_023
#define 	PL_CHRLEFTTM_3   								 DATABASE_UINT16_024
#define 	PL_CHRLEFTTM_4   								 DATABASE_UINT16_025

#define 	PL_CHRUSEDTM_1   								 DATABASE_UINT16_026
#define 	PL_CHRUSEDTM_2   								 DATABASE_UINT16_027
#define 	PL_CHRUSEDTM_3   								 DATABASE_UINT16_028
#define 	PL_CHRUSEDTM_4   								 DATABASE_UINT16_029

#define 	PL_TOTALAH_1   								 	DATABASE_UINT16_030
#define 	PL_TOTALAH_2   								 	DATABASE_UINT16_031
#define 	PL_TOTALAH_3   								 	DATABASE_UINT16_032
#define 	PL_TOTALAH_4   								 	DATABASE_UINT16_033

#define 	PL_GETNEEDCHARGUNNUM                DATABASE_UINT16_034
#define 	PL_GETNEEDSTOPGUNNUM                DATABASE_UINT16_035

#define 	PL_DATABASE_UINT16_STOP			 DATABASE_UINT16_035

/*                                              	                      
 *	< FLOAT32  REMAP SECTION >                    	                      
 */
#define 	PL_DATABASE_FLOAT32_START	               DATABASE_FLOAT32_000
#define 	PL_MAINCARD_LEFTMONEY	             		 DATABASE_FLOAT32_000
#define 	PL_CHRUSED_TOTALMONEY				 DATABASE_FLOAT32_001
#define 	PL_CHROUTPT_VOLT						 DATABASE_FLOAT32_002
#define 	PL_CHROUTPT_CURRENT					 DATABASE_FLOAT32_003
#define 	PL_CHRSTART_KWH						 DATABASE_FLOAT32_004
#define 	PL_CHRCURRRENT_KWH					 DATABASE_FLOAT32_005
#define 	PL_CHRUSED_KWH					 	 DATABASE_FLOAT32_006
#define 	PL_LOWESTCELL_TEMP					 DATABASE_FLOAT32_007
#define 	PL_HIGESTCELL_TEMP					 DATABASE_FLOAT32_008
#define 	PL_OUTPUT_POWER					 	 DATABASE_FLOAT32_009
#define 	PL_CHARGESEVICE_MONEY				DATABASE_FLOAT32_010
#define 	PL_ELECTRIC_MONEY						DATABASE_FLOAT32_011
#define 	PL_SINGLE_HIGHVOLT					DATABASE_FLOAT32_012
#define 	PL_SINGLE_LOWVOLT						DATABASE_FLOAT32_013
#define 	PL_MODULE_HIGH_TEMP					DATABASE_FLOAT32_014
#define 	PL_TOP1_ELECPRICE						DATABASE_FLOAT32_015
#define 	PL_TOP1_STARTTM						DATABASE_FLOAT32_016
#define 	PL_TOP1_STOPTM						DATABASE_FLOAT32_017
#define 	PL_PEAK1_ELECPRICE					DATABASE_FLOAT32_018
#define 	PL_PEAK1_STARTTM						DATABASE_FLOAT32_019
#define 	PL_PEAK1_STOPTM						DATABASE_FLOAT32_020
#define 	PL_FLAT1_ELECPRICE					DATABASE_FLOAT32_021
#define 	PL_FLAT1_STARTTM						DATABASE_FLOAT32_022
#define 	PL_FLAT1_STOPTM						DATABASE_FLOAT32_023
#define 	PL_VALLEY1_ELECPRICE					DATABASE_FLOAT32_024
#define 	PL_VALLEY1_STARTTM					DATABASE_FLOAT32_025
#define 	PL_VALLEY1_STOPTM						DATABASE_FLOAT32_026
#define 	PL_TOP2_ELECPRICE						DATABASE_FLOAT32_027
#define 	PL_TOP2_STARTTM						DATABASE_FLOAT32_028
#define 	PL_TOP2_STOPTM						DATABASE_FLOAT32_029
#define 	PL_PEAK2_ELECPRICE					DATABASE_FLOAT32_030
#define 	PL_PEAK2_STARTTM						DATABASE_FLOAT32_031
#define 	PL_PEAK2_STOPTM						DATABASE_FLOAT32_032
#define 	PL_FLAT2_ELECPRICE					DATABASE_FLOAT32_033
#define 	PL_FLAT2_STARTTM						DATABASE_FLOAT32_034
#define 	PL_FLAT2_STOPTM						DATABASE_FLOAT32_035
#define 	PL_VALLEY2_ELECPRICE					DATABASE_FLOAT32_036
#define 	PL_VALLEY2_STARTTM					DATABASE_FLOAT32_037
#define 	PL_VALLEY2_STOPTM						DATABASE_FLOAT32_038

#define  PL_MOUDLE_OUTPUTVOLT_1           DATABASE_FLOAT32_039
#define  PL_MOUDLE_OUTPUTVOLT_2           DATABASE_FLOAT32_040
#define  PL_MOUDLE_OUTPUTVOLT_3           DATABASE_FLOAT32_041
#define  PL_MOUDLE_OUTPUTVOLT_4           DATABASE_FLOAT32_042
#define  PL_MOUDLE_OUTPUTVOLT_5           DATABASE_FLOAT32_043
#define  PL_MOUDLE_OUTPUTVOLT_6           DATABASE_FLOAT32_044
#define  PL_MOUDLE_OUTPUTVOLT_7           DATABASE_FLOAT32_045
#define  PL_MOUDLE_OUTPUTVOLT_8           DATABASE_FLOAT32_046
#define  PL_MOUDLE_OUTPUTVOLT_9           DATABASE_FLOAT32_047
#define  PL_MOUDLE_OUTPUTVOLT_10           DATABASE_FLOAT32_048
#define  PL_MOUDLE_OUTPUTVOLT_11           DATABASE_FLOAT32_049
#define  PL_MOUDLE_OUTPUTVOLT_12           DATABASE_FLOAT32_050
#define  PL_MOUDLE_OUTPUTVOLT_13           DATABASE_FLOAT32_051
#define  PL_MOUDLE_OUTPUTVOLT_14           DATABASE_FLOAT32_052
#define  PL_MOUDLE_OUTPUTVOLT_15           DATABASE_FLOAT32_053
#define  PL_MOUDLE_OUTPUTVOLT_16           DATABASE_FLOAT32_054

#define  PL_MOUDLE_OUTPUTCUR_1           DATABASE_FLOAT32_055
#define  PL_MOUDLE_OUTPUTCUR_2           DATABASE_FLOAT32_056
#define  PL_MOUDLE_OUTPUTCUR_3           DATABASE_FLOAT32_057
#define  PL_MOUDLE_OUTPUTCUR_4           DATABASE_FLOAT32_058
#define  PL_MOUDLE_OUTPUTCUR_5           DATABASE_FLOAT32_059
#define  PL_MOUDLE_OUTPUTCUR_6           DATABASE_FLOAT32_060
#define  PL_MOUDLE_OUTPUTCUR_7           DATABASE_FLOAT32_061
#define  PL_MOUDLE_OUTPUTCUR_8           DATABASE_FLOAT32_062
#define  PL_MOUDLE_OUTPUTCUR_9           DATABASE_FLOAT32_063
#define  PL_MOUDLE_OUTPUTCUR_10           DATABASE_FLOAT32_064
#define  PL_MOUDLE_OUTPUTCUR_11           DATABASE_FLOAT32_065
#define  PL_MOUDLE_OUTPUTCUR_12          DATABASE_FLOAT32_066
#define  PL_MOUDLE_OUTPUTCUR_13           DATABASE_FLOAT32_067
#define  PL_MOUDLE_OUTPUTCUR_14           DATABASE_FLOAT32_068
#define  PL_MOUDLE_OUTPUTCUR_15           DATABASE_FLOAT32_069
#define  PL_MOUDLE_OUTPUTCUR_16           DATABASE_FLOAT32_070

#define  PL_HANDSET_VOLT                            DATABASE_FLOAT32_071
#define  PL_HANDSET_CURRENT                     DATABASE_FLOAT32_072

#define   CHRVOLTMESURVALUE_1                   DATABASE_FLOAT32_073
#define   CHRVOLTMESURVALUE_2                   DATABASE_FLOAT32_074
#define   CHRVOLTMESURVALUE_3                   DATABASE_FLOAT32_075
#define   CHRVOLTMESURVALUE_4                   DATABASE_FLOAT32_076

#define   CHRCURMESURVALUE_1                    DATABASE_FLOAT32_077
#define   CHRCURMESURVALUE_2                    DATABASE_FLOAT32_078
#define   CHRCURMESURVALUE_3                    DATABASE_FLOAT32_079
#define   CHRCURMESURVALUE_4                    DATABASE_FLOAT32_080

#define   BMS_VOLTNEED_1                   	       		DATABASE_FLOAT32_081
#define   BMS_VOLTNEED_2                   	       		DATABASE_FLOAT32_082
#define   BMS_VOLTNEED_3                   	       		DATABASE_FLOAT32_083
#define   BMS_VOLTNEED_4                   	       		DATABASE_FLOAT32_084

#define   BMS_CURNEED_1                   	      	 DATABASE_FLOAT32_085
#define   BMS_CURNEED_2                   	      	 DATABASE_FLOAT32_086
#define   BMS_CURNEED_3                   	      	 DATABASE_FLOAT32_087
#define   BMS_CURNEED_4                   	      	 DATABASE_FLOAT32_088

#define   START_KWH_1                   					DATABASE_FLOAT32_089
#define   START_KWH_2                   					DATABASE_FLOAT32_090
#define   START_KWH_3                   					DATABASE_FLOAT32_091
#define   START_KWH_4                   					DATABASE_FLOAT32_092

#define   CURRENT_KWH_1                   				DATABASE_FLOAT32_093
#define   CURRENT_KWH_2                   				DATABASE_FLOAT32_094
#define   CURRENT_KWH_3                   				DATABASE_FLOAT32_095
#define   CURRENT_KWH_4                   				DATABASE_FLOAT32_096

#define   USED_KWH_1                   						DATABASE_FLOAT32_097
#define   USED_KWH_2                   						DATABASE_FLOAT32_098
#define   USED_KWH_3                   						DATABASE_FLOAT32_099
#define   USED_KWH_4                   						DATABASE_FLOAT32_100

#define   STOP_KWH_1                   						DATABASE_FLOAT32_101
#define   STOP_KWH_2                   						DATABASE_FLOAT32_102
#define   STOP_KWH_3                   						DATABASE_FLOAT32_103
#define   STOP_KWH_4                   						DATABASE_FLOAT32_104

#define   HIGESTSINGLEVOLT_1                   	DATABASE_FLOAT32_105
#define   HIGESTSINGLEVOLT_2                   	DATABASE_FLOAT32_106
#define   HIGESTSINGLEVOLT_3                   	DATABASE_FLOAT32_107
#define   HIGESTSINGLEVOLT_4                   	DATABASE_FLOAT32_108

#define   HIGESTSINGLETEMP_1                   	DATABASE_FLOAT32_109
#define   HIGESTSINGLETEMP_2                   	DATABASE_FLOAT32_110
#define   HIGESTSINGLETEMP_3                   	DATABASE_FLOAT32_111
#define   HIGESTSINGLETEMP_4                   	DATABASE_FLOAT32_112

#define   OUTPUTPOWER_1                   				DATABASE_FLOAT32_113
#define   OUTPUTPOWER_2                  				DATABASE_FLOAT32_114
#define   OUTPUTPOWER_3                   				DATABASE_FLOAT32_115
#define   OUTPUTPOWER_4                   				DATABASE_FLOAT32_116

#define   USERNEEDCHAR_KWH_1                   	DATABASE_FLOAT32_117
#define   USERNEEDCHAR_KWH_2                   	DATABASE_FLOAT32_118
#define   USERNEEDCHAR_KWH_3                   	DATABASE_FLOAT32_119
#define   USERNEEDCHAR_KWH_4                   	DATABASE_FLOAT32_120

#define   USERCARD_LEFTMONEY_1                   DATABASE_FLOAT32_121
#define   USERCARD_LEFTMONEY_2                   DATABASE_FLOAT32_122
#define   USERCARD_LEFTMONEY_3                   DATABASE_FLOAT32_123
#define   USERCARD_LEFTMONEY_4                   DATABASE_FLOAT32_124

#define   USERCARD_USEDTOTALMONEY_1      DATABASE_FLOAT32_125
#define   USERCARD_USEDTOTALMONEY_2      DATABASE_FLOAT32_126
#define   USERCARD_USEDTOTALMONEY_3      DATABASE_FLOAT32_127
#define   USERCARD_USEDTOTALMONEY_4      DATABASE_FLOAT32_128

#define   CHARGESERVICE_MONEY_1                 DATABASE_FLOAT32_129
#define   CHARGESERVICE_MONEY_2                 DATABASE_FLOAT32_130
#define   CHARGESERVICE_MONEY_3                 DATABASE_FLOAT32_131
#define   CHARGESERVICE_MONEY_4                 DATABASE_FLOAT32_132

#define   USEDELECTRIC_MONEY_1                    DATABASE_FLOAT32_133
#define   USEDELECTRIC_MONEY_2                    DATABASE_FLOAT32_134
#define   USEDELECTRIC_MONEY_3                    DATABASE_FLOAT32_135
#define   USEDELECTRIC_MONEY_4                    DATABASE_FLOAT32_136

#define   CHARGEKWH_FRMNETWORK_1           DATABASE_FLOAT32_137
#define   CHARGEKWH_FRMNETWORK_2           DATABASE_FLOAT32_138
#define   CHARGEKWH_FRMNETWORK_3           DATABASE_FLOAT32_139
#define   CHARGEKWH_FRMNETWORK_4           DATABASE_FLOAT32_140

#define 	PL_DATABASE_FLOAT32_STOP			DATABASE_FLOAT32_140


//[ARRAY]
#define 	PL_DATABASE_ARRAY_START			 DATABASE_ARRAY_000
#define 	PL_MAINCARD_SN                          		 DATABASE_ARRAY_000  
#define 	PL_CHR_STARTTIME					 DATABASE_ARRAY_001 
#define 	PL_CHR_STOPTIME					 DATABASE_ARRAY_002
#define 	PL_HMI_CARD_PASSWD				 DATABASE_ARRAY_003
#define 	PL_CHRTOTALUSE_TIME_ARRAY		 DATABASE_ARRAY_004
#define 	PL_SETPAGE_PASSWD				 DATABASE_ARRAY_005
//#define 	PL_DATABASE_ARRAY_STOP			 DATABASE_ARRAY_005
#define   PL_BOOKCARD_SN                  			  DATABASE_ARRAY_006
#define   PL_GUEST_NAME                  			  DATABASE_ARRAY_007
#define 	PL_DATABASE_ARRAY_STOP			 DATABASE_ARRAY_007

//【u32】add by mj_1_29
#define   PL_DATABASE_U32_START			DATABASE_UINT32_000

#define   PL_STUBERRSTATE_FLAG				DATABASE_UINT32_000
#define   PL_BOOKDOWN_TIME					DATABASE_UINT32_001
#define   PL_BOOKSTART_TIME				 	   DATABASE_UINT32_002
#define   PL_BOOKCARD_ERR				   	 DATABASE_UINT32_003

#define   PL_USERNEED_TIME_1				   	 DATABASE_UINT32_004
#define   PL_USERNEED_TIME_2				   	 DATABASE_UINT32_005
#define   PL_USERNEED_TIME_3				   	 DATABASE_UINT32_006
#define   PL_USERNEED_TIME_4				   	 DATABASE_UINT32_007

#define   PL_STOPSOCFRMNETWORK_1				   	 DATABASE_UINT32_008
#define   PL_STOPSOCFRMNETWORK_2				   	 DATABASE_UINT32_009
#define   PL_STOPSOCFRMNETWORK_3				   	 DATABASE_UINT32_010
#define   PL_STOPSOCFRMNETWORK_4				   	 DATABASE_UINT32_011

#define   PL_CHARGETIME_FRMNETWORK_1				   	 DATABASE_UINT32_012
#define   PL_CHARGETIME_FRMNETWORK_2				   	 DATABASE_UINT32_013
#define   PL_CHARGETIME_FRMNETWORK_3				   	 DATABASE_UINT32_014
#define   PL_CHARGETIME_FRMNETWORK_4				   	 DATABASE_UINT32_015

#define   PL_STARTCHR_TM_1				   	 DATABASE_UINT32_016
#define   PL_STARTCHR_TM_2				   	 DATABASE_UINT32_017
#define   PL_STARTCHR_TM_3				   	 DATABASE_UINT32_018
#define   PL_STARTCHR_TM_4				   	 DATABASE_UINT32_019

#define   PL_CURCHR_TM_1				   	 DATABASE_UINT32_020
#define   PL_CURCHR_TM_2				   	 DATABASE_UINT32_021
#define   PL_CURCHR_TM_3				   	 DATABASE_UINT32_022
#define   PL_CURCHR_TM_4				   	 DATABASE_UINT32_023

#define   PL_STOPCHR_TM_1				   	 DATABASE_UINT32_024
#define   PL_STOPCHR_TM_2				   	 DATABASE_UINT32_025
#define   PL_STOPCHR_TM_3				   	 DATABASE_UINT32_026
#define   PL_STOPCHR_TM_4				   	 DATABASE_UINT32_027

#define   PL_STARTCHR_SYSTM_1				   	 DATABASE_UINT32_028
#define   PL_STARTCHR_SYSTM_2				   	 DATABASE_UINT32_029
#define   PL_STARTCHR_SYSTM_3				   	 DATABASE_UINT32_030
#define   PL_STARTCHR_SYSTM_4				   	 DATABASE_UINT32_031

#define   PL_STOPCHR_SYSTM_1				   	 DATABASE_UINT32_032
#define   PL_STOPCHR_SYSTM_2			   	 DATABASE_UINT32_033
#define   PL_STOPCHR_SYSTM_3				   	 DATABASE_UINT32_034
#define   PL_STOPCHR_SYSTM_4				   	 DATABASE_UINT32_035

#define   PL_DATABASE_U32_STOP				DATABASE_UINT32_035

/*                                                      
 *	<OHTERS REMAP>                                  
 */                                                     
#define DB_ARRARY_TYPE_BUFFER_LEN       150
#define DEV_MAX_DEVICE_NUMBER		6
#define DEV_MAX_SLOT_NUMBER             6
#define SOFTWARE_MAX_SLOT_NUMBER	(DEV_MAX_DEVICE_NUMBER*DEV_MAX_SLOT_NUMBER)


#endif /* IOREMAP_H_ */                                 
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
                                                        
